name = "gsv"
version = "5.0.1"
description = "A simple csv parser and generator written in Gleam"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "gsv" }

[dependencies]
gleam_stdlib = ">= 0.69.0 and < 1.0.0"
glearray = ">= 1.0.0 and < 3.0.0"
splitter = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
